# Generated by Django 4.2.30 on 2026-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0004_center_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='center',
        ),
        migrations.AddField(
            model_name='project',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='centers_and_projects.center'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
