# Generated by Django 4.2.30 on 2026-09-12 12:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0005_remove_project_center_project_centers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_stages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('QURAN', 'مشروع قرآني'), ('CUSTOM', 'مشروع مخصص (منهجي)')], default='QURAN', max_length=20),
        ),
        migrations.CreateModel(
            name='StagePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('part_type', models.CharField(choices=[('DEFAULT_QURAN', 'جزء قرآني افتراضي'), ('CUSTOM', 'جزء مخصص')], default='DEFAULT_QURAN', max_length=20)),
                ('juz_number', models.IntegerField(blank=True, null=True)),
                ('start_page', models.IntegerField(default=1)),
                ('end_page', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='centers_and_projects.projectstage')),
            ],
            options={
                'db_table': 'stage_parts',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='centers_and_projects.project'),
        ),
    ]
