# Generated by Django 4.2.30 on 2026-09-12 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_reached_page'),
        ('students_and_parents', '0002_student_reached_page_studentenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centers_and_projects', '0006_projectstage_project_project_type_stagepart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('pass_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_templates',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='require_exam_for_all_stages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='has_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='centers_and_projects.center')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_notifications',
            },
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'بانتظار إجراء الامتحان'), ('SCHEDULED', 'تم تحديد موعد الامتحان'), ('PASSED', 'ناجح'), ('FAILED', 'راسب')], default='PENDING', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='centers_and_projects.examtemplate')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='centers_and_projects.projectstage')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students_and_parents.student')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.userprofile')),
            ],
            options={
                'db_table': 'student_exam_results',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'أتمتة (اختيار من متعدد)'), ('ESSAY', 'تحريري')], default='MULTIPLE_CHOICE', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('points', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('order', models.IntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='centers_and_projects.examtemplate')),
            ],
            options={
                'db_table': 'exam_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='exam_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='centers_and_projects.examtemplate'),
        ),
    ]
