# Generated by Django 4.2.30 on 2026-09-12 12:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0007_examtemplate_project_require_exam_for_all_stages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluation_templates',
            },
        ),
        migrations.CreateModel(
            name='EvaluationGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('requires_repeat', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('color_code', models.CharField(blank=True, max_length=30, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='centers_and_projects.evaluationtemplate')),
            ],
            options={
                'db_table': 'evaluation_grades',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='centers_and_projects.evaluationtemplate'),
        ),
    ]
