# Generated by Django 4.2 on 2026-10-01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0008_evaluationtemplate_evaluationgrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueWeeklySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(default='2026-02', max_length=7)),
                ('week_number', models.IntegerField(default=1)),
                ('day_of_week', models.IntegerField(default=0)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(11, 0))),
                ('session_title', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='centers_and_projects.center')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='centers_and_projects.project')),
            ],
            options={
                'db_table': 'mosque_weekly_schedules',
                'ordering': ['week_number', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='mosqueweeklyschedule',
            constraint=models.UniqueConstraint(fields=('center', 'project', 'month', 'week_number', 'day_of_week'), name='unique_center_project_schedule_slot'),
        ),
    ]
