# Generated by Django 4.2.30 on 2026-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0010_project_test_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgrade',
            name='stop_test_action',
            field=models.CharField(blank=True, default='لا', max_length=30, null=True),
        ),
    ]
