# Generated by Django 4.2.30 on 2026-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0011_evaluationgrade_stop_test_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_rewards_store_enabled',
            field=models.BooleanField(default=True, help_text='التحكم بفتح أو إغلاق متجر المكافآت على مستوى المركز'),
        ),
    ]
