"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@_w-86x@gtu8giul7e((1smsgg4^o2=pk(r5tjhfjsr=3y7$**'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'tenant-id',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'corsheaders',
    'rest_framework',
    # Master apps (core_system)
    'core_system.tenants',
    'core_geodata',
    'core_system.subscriptions',
    'core_system.payments',
    'core_system.backups',
    # Tenant apps (tenant_modules)
    'tenant_modules.users',
    'tenant_modules.centers_and_projects',
    'tenant_modules.halaqat',
    'tenant_modules.students_and_parents',
    'tenant_modules.attendance',
    'tenant_modules.recitation_and_sabr',
    'tenant_modules.reports_and_certificates',
    'tenant_modules.points_and_rewards',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core_system.middleware.TenantJWTAuthMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'manara_db',
        'USER': 'manara_user',
        'PASSWORD': 'M@nara_2026_Str0ng!',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# الملفات المرفوعة (شعارات المساجد)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# الحد الأقصى لحجم شعار المسجد (2MB)
TENANT_LOGO_MAX_BYTES = 2 * 1024 * 1024

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

# config/settings.py

# توجيه ملفات الترحيل (Migrations) لمجلدات مخصصة بناءً على الهيكلية
MIGRATION_MODULES = {
    # تطبيقات النظام المركزي (Master DB)
    'tenants': 'migrations.master.tenants',
    'subscriptions': 'migrations.master.subscriptions',
    'payments': 'migrations.master.payments',
    'backups': 'migrations.master.backups',
    
    # تطبيقات قالب المسجد (Tenant DB Template)
    'users': 'migrations.tenant_template.users',
    'centers_and_projects': 'migrations.tenant_template.centers_and_projects',
    'halaqat': 'migrations.tenant_template.halaqat',
    'students_and_parents': 'migrations.tenant_template.students_and_parents',
    'attendance': 'migrations.tenant_template.attendance',
    'recitation_and_sabr': 'migrations.tenant_template.recitation_and_sabr',
    'reports_and_certificates': 'migrations.tenant_template.reports_and_certificates',
    'points_and_rewards': 'migrations.tenant_template.points_and_rewards',
}

# تفعيل موجه قواعد البيانات
DATABASE_ROUTERS = ['config.database_router.TenantRouter']