# Generated by Django 4.2.30 on 2026-10-01 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancelog_behavior_attendancelog_is_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_date', models.DateField()),
                ('new_date', models.DateField()),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('changed_by_name', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'session_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='check_in_time',
        ),
        migrations.AlterField(
            model_name='halaqasession',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='halaqasession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='halaqasession',
            constraint=models.UniqueConstraint(fields=('halaqa_id', 'session_date'), name='unique_halaqa_session_per_date'),
        ),
        migrations.AddField(
            model_name='sessionauditlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.halaqasession'),
        ),
    ]
