# Generated by Django 4.2.30 on 2026-09-20 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
        ('halaqat', '0005_remove_halaqa_max_students'),
        ('centers_and_projects', '0008_evaluationtemplate_evaluationgrade_and_more'),
        ('students_and_parents', '0004_student_current_residence_student_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='general_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='income_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_orphan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_orphan', models.BooleanField(default=False)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_notes', models.TextField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('current_residence', models.CharField(blank=True, max_length=200, null=True)),
                ('income_level', models.CharField(blank=True, max_length=50, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('reached_page', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers_and_projects.stagepart')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers_and_projects.projectstage')),
                ('halaqa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halaqat.halaqa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers_and_projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_registration_requests', to='users.userprofile')),
            ],
            options={
                'db_table': 'student_registration_requests',
            },
        ),
    ]
