# Generated by Django 4.2.30 on 2026-09-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_parents', '0005_student_general_notes_student_has_special_needs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'طلب تسجيل طالب جديد'), ('UPDATE', 'طلب تعديل بيانات طالب')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_requests', to='students_and_parents.student'),
        ),
    ]
