# Generated by Django 4.2.30 on 2026-09-30 19:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_roles'),
        ('students_and_parents', '0007_evaluationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_deletion_requests', to='users.userprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to='users.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='students_and_parents.student')),
            ],
            options={
                'db_table': 'student_deletion_requests',
            },
        ),
    ]
