# Generated by Django 4.2.30 on 2026-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_parents', '0009_studentregistrationrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdeletionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى بواسطة المعلم')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentregistrationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغى بواسطة المعلم')], default='PENDING', max_length=20),
        ),
    ]
