# Generated by Django 4.2.30 on 2026-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_parents', '0010_alter_studentdeletionrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
