# Generated by Django 4.2.30 on 2026-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0003_center_latitude_center_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
