# Generated by Django 4.2.30 on 2026-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_guardian_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reached_page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
