# Generated by Django 4.2.30 on 2026-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
