# Generated by Django 4.2.30 on 2026-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points_and_rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardclaim',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='ملاحظات الإدارة للطالب', null=True),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='سبب الرفض إن وجد', null=True),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات الطالب / ولي الأمر عند الطلب', null=True),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'تمت الموافقة'), ('DELIVERED', 'تم التسليم'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=20),
        ),
    ]
