# Generated by Django 4.2.30 on 2026-10-03 10:44

from django.db import migrations, models


def sanitize_stock_quantity(apps, schema_editor):
    Reward = apps.get_model('points_and_rewards', 'Reward')
    Reward.objects.filter(stock_quantity__lt=0).update(stock_quantity=0)

def reverse_sanitize_stock_quantity(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('points_and_rewards', '0002_rewardclaim_admin_notes_rewardclaim_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='رقم يمثل المخزون المتاح'),
        ),
        migrations.RunPython(sanitize_stock_quantity, reverse_sanitize_stock_quantity),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(check=models.Q(('stock_quantity__gte', 0)), name='reward_stock_non_negative'),
        ),
    ]
