# Generated by Django 4.2.30 on 2026-10-02 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students_and_parents', '0010_alter_studentdeletionrequest_status_and_more'),
        ('centers_and_projects', '0011_evaluationgrade_stop_test_action'),
        ('users', '0006_userprofile_roles'),
        ('halaqat', '0005_remove_halaqa_max_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='مدة الحل بالدقائق')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='عدد المحاولات المسموحة')),
                ('points_reward', models.PositiveIntegerField(default=10, help_text='النقاط الممنوحة عند الاجتياز أو الفوز')),
                ('is_published', models.BooleanField(default=True)),
                ('target_all_centers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to='users.userprofile')),
                ('target_centers', models.ManyToManyField(blank=True, related_name='competitions', to='centers_and_projects.center')),
                ('target_halaqat', models.ManyToManyField(blank=True, related_name='competitions', to='halaqat.halaqa')),
            ],
            options={
                'db_table': 'competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'جارية'), ('SUBMITTED', 'تم التسليم'), ('GRADED', 'تم التصحيح والاعتماد')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_possible_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('points_awarded', models.IntegerField(default=0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='points_and_rewards.competition')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_competitions', to='users.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_participations', to='students_and_parents.student')),
            ],
            options={
                'db_table': 'competition_participations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'اختيار من متعدد (مؤتمت)'), ('TRUE_FALSE', 'صح أو خطأ (مؤتمت)'), ('ESSAY', 'سؤال تحريري / مقالي'), ('MATCHING', 'مطابقة')], default='MULTIPLE_CHOICE', max_length=25)),
                ('options', models.JSONField(blank=True, default=list, help_text='قائمة الخيارات للأسئلة المؤتمتة')),
                ('correct_answer', models.TextField(blank=True, help_text='الإجابة الصحيحة للأسئلة المؤتمتة أو معيار التصحيح للمقالي')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='points_and_rewards.competition')),
            ],
            options={
                'db_table': 'competition_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, help_text='رابط الصورة أو كود الصورة', null=True)),
                ('points_cost', models.PositiveIntegerField(default=50, help_text='عدد النقاط المطلوبة للاستبدال')),
                ('stock_quantity', models.IntegerField(default=-1, help_text='-1 تعني كمية غير محدودة، أو رقم يمثل المخزون المتاح')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='centers_and_projects.center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rewards', to='users.userprofile')),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'تمت الموافقة'), ('DELIVERED', 'تم التسليم'), ('REJECTED', 'مرفوض'), ('CANCELLED', 'ملغي')], default='DELIVERED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to='users.userprofile')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='points_and_rewards.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to='students_and_parents.student')),
            ],
            options={
                'db_table': 'reward_claims',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='points_and_rewards.competitionparticipation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points_and_rewards.competitionquestion')),
            ],
            options={
                'db_table': 'competition_question_answers',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='القيمة المضافة (موجبة) أو المخصومة (سالبة)')),
                ('transaction_type', models.CharField(choices=[('BEHAVIORAL_BONUS', 'مكافأة سلوكية (+2)'), ('REWARD_REDEMPTION', 'استبدال مكافأة'), ('COMPETITION_PRIZE', 'جائزة مسابقة'), ('ATTENDANCE', 'حضور وجلسات'), ('RECITATION', 'تسميع وإنجاز'), ('MANUAL_ADJUSTMENT', 'تعديل يدوي'), ('REFUND', 'استرجاع نقاط')], default='BEHAVIORAL_BONUS', max_length=30)),
                ('reason', models.TextField(help_text='سبب العملية')),
                ('balance_before', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_point_transactions', to='users.userprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='students_and_parents.student')),
            ],
            options={
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='points_and_rewards.competition')),
            ],
            options={
                'db_table': 'competition_sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='competitionquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='points_and_rewards.competitionsection'),
        ),
    ]
