# Generated by Django 4.2.30 on 2026-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0002_center_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
