# Generated by Django 4.2.30 on 2026-09-05 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecitationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('recitation_type', models.CharField(choices=[('NEW_MEMORIZATION', 'حفظ جديد'), ('MINOR_REVIEW', 'مراجعة صغرى'), ('MAJOR_REVIEW', 'مراجعة كبرى')], max_length=30)),
                ('from_surah', models.IntegerField()),
                ('from_ayah', models.IntegerField()),
                ('to_surah', models.IntegerField()),
                ('to_ayah', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
                ('memorization_mistakes_count', models.IntegerField(default=0)),
                ('tajweed_mistakes_count', models.IntegerField(default=0)),
                ('audio_note_s3_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancelog')),
            ],
            options={
                'db_table': 'recitation_logs',
            },
        ),
    ]
