# Generated by Django 4.2.30 on 2026-09-05 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('subdomain', models.CharField(max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('db_name', models.CharField(max_length=63, unique=True)),
                ('db_host', models.CharField(default='localhost', max_length=255)),
                ('db_port', models.IntegerField(default=5432)),
                ('db_user', models.CharField(max_length=63)),
                ('db_password_hash', models.TextField()),
                ('admin_password_hash', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'indexes': [models.Index(fields=['subdomain'], name='tenants_subdoma_69cf01_idx')],
            },
        ),
    ]
