# Generated by Django 4.2.30 on 2026-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_rewards_store_enabled',
            field=models.BooleanField(default=True, help_text='فتح أو إغلاق متجر المكافآت على مستوى المسجد'),
        ),
    ]
