# Generated by Django 4.2.30 on 2026-09-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='halaqa',
            table='halaqat',
        ),
    ]
