# Generated by Django 4.2.30 on 2026-09-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0006_projectstage_project_project_type_stagepart_and_more'),
        ('halaqat', '0003_halaqa_deleted_at_halaqa_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqa',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqat', to='centers_and_projects.project'),
        ),
    ]
