# Generated by Django 4.2.30 on 2026-09-12 12:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalaqaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('halaqa_id', models.UUIDField()),
                ('teacher_id', models.UUIDField(blank=True, null=True)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'halaqa_sessions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='behavior_score',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غائب'), ('EXCUSED', 'مستأذن'), ('LATE', 'متأخر')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='teacher_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='attendance.halaqasession'),
        ),
    ]
