# Generated by Django 4.2.30 on 2026-09-12 12:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_reached_page'),
        ('centers_and_projects', '0006_projectstage_project_project_type_stagepart_and_more'),
        ('halaqat', '0004_halaqa_project'),
        ('students_and_parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reached_page',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reached_page', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='centers_and_projects.stagepart')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='centers_and_projects.projectstage')),
                ('halaqa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='halaqat.halaqa')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='centers_and_projects.project')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students_and_parents.student')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.userprofile')),
            ],
            options={
                'db_table': 'student_enrollments',
            },
        ),
    ]
