# Generated by Django 4.2.30 on 2026-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_and_parents', '0002_student_reached_page_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
