# Generated by Django 4.2.30 on 2026-09-30 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_active'),
        ('halaqat', '0005_remove_halaqa_max_students'),
        ('students_and_parents', '0006_studentregistrationrequest_request_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_type', models.CharField(choices=[('MEMORIZATION', 'حفظ'), ('BEHAVIOR', 'سلوك')], max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('halaqa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='halaqat.halaqa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='students_and_parents.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to='users.userprofile')),
            ],
            options={
                'db_table': 'evaluation_logs',
                'indexes': [models.Index(fields=['student', 'evaluation_type', 'date'], name='evaluation__student_b5ef92_idx')],
            },
        ),
    ]
