# Generated by Django 4.2.30 on 2026-09-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0002_alter_halaqa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqa',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='halaqa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
