# Generated by Django 4.2.30 on 2026-09-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaqat', '0004_halaqa_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halaqa',
            name='max_students',
        ),
    ]
