# Generated by Django 4.2.30 on 2026-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_father_phone_userprofile_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guardian_type',
            field=models.CharField(blank=True, choices=[('FATHER', 'الأب'), ('MOTHER', 'الأم')], default='FATHER', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
