# Generated by Django 4.2.30 on 2026-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='parent_user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('TENANT_ADMIN', 'Tenant Admin'), ('CENTER_MANAGER', 'Center Manager'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=50),
        ),
    ]
