# Generated by Django 4.2.30 on 2026-09-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers_and_projects', '0008_evaluationtemplate_evaluationgrade_and_more'),
        ('attendance', '0002_halaqasession_alter_attendancelog_unique_together_and_more'),
        ('recitation_and_sabr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitationlog',
            name='behavior_score',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='recitationlog',
            name='evaluation_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recitations', to='centers_and_projects.evaluationgrade'),
        ),
        migrations.AddField(
            model_name='recitationlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recitationlog',
            name='page_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recitationlog',
            name='requires_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='attendance.attendancelog'),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='from_ayah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='from_surah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='recitation_type',
            field=models.CharField(choices=[('NEW_MEMORIZATION', 'حفظ جديد'), ('MINOR_REVIEW', 'مراجعة صغرى'), ('MAJOR_REVIEW', 'مراجعة كبرى')], default='NEW_MEMORIZATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='to_ayah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recitationlog',
            name='to_surah',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
